// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtPh9Wg2rmaiZXyGu6bDW3bSJ8hjG74Z4',
    appId: '1:732559947107:web:20d67b6b4cdd173e610f56',
    messagingSenderId: '732559947107',
    projectId: 'flutter-my-app-73f61',
    authDomain: 'flutter-my-app-73f61.firebaseapp.com',
    storageBucket: 'flutter-my-app-73f61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF8zrvl3u-EenwhA95pwO63RLMCnKAagc',
    appId: '1:732559947107:android:e048e4c6c8e2f7e4610f56',
    messagingSenderId: '732559947107',
    projectId: 'flutter-my-app-73f61',
    storageBucket: 'flutter-my-app-73f61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWYhltbDZXPuKKQI4kkHbk6tPK40ckZg',
    appId: '1:732559947107:ios:9713199a311cbc88610f56',
    messagingSenderId: '732559947107',
    projectId: 'flutter-my-app-73f61',
    storageBucket: 'flutter-my-app-73f61.appspot.com',
    iosClientId: '732559947107-r5q32alec1ot20gbbr1l3mgr2a0ju7ua.apps.googleusercontent.com',
    iosBundleId: 'com.callor.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhWYhltbDZXPuKKQI4kkHbk6tPK40ckZg',
    appId: '1:732559947107:ios:76e16a3f2c093890610f56',
    messagingSenderId: '732559947107',
    projectId: 'flutter-my-app-73f61',
    storageBucket: 'flutter-my-app-73f61.appspot.com',
    iosClientId: '732559947107-kafk3kfhaknht0bs2j6tlgva239rb1n8.apps.googleusercontent.com',
    iosBundleId: 'com.callor.firebase.RunnerTests',
  );
}
